webhook {
  url = ${?WEBHOOK_URL}
  metagraph-id = ${?CL_L0_TOKEN_IDENTIFIER}
}

hydration {
  self-url = ${?COMMITTED_HYDRATION_SELF_URL}
  peers = ${?COMMITTED_HYDRATION_PEERS}
  interval = ${?COMMITTED_HYDRATION_INTERVAL}
}
