package xyz.kd5ujc.shared_test

import cats.effect.IO

import io.constellationnetwork.security.SecurityProvider

import weaver.SimpleIOSuite

object ParticipantRegistryTest extends SimpleIOSuite {

  test("fromResources loads all 26 participants") {
    SecurityProvider.forAsync[IO].use { implicit sp =>
      Participant.ParticipantRegistry.fromResources[IO]().map { registry =>
        val addresses = registry.addresses
        expect(addresses.size == 26)
      }
    }
  }

  test("fromResources produces deterministic addresses") {
    SecurityProvider.forAsync[IO].use { implicit sp =>
      Participant.ParticipantRegistry.fromResources[IO]().map { registry =>
        val aliceAddr = registry(Participant.Alice).address
        // Address generated by cl-keytool + cl-wallet
        expect(aliceAddr.value.value == "DAG6HdXmFyEwgKKdaEyAjU6SJPxGNAjUSbHgiRct")
      }
    }
  }

  test("fromResources participants can sign messages") {
    import java.util.UUID
    import xyz.kd5ujc.schema.Updates
    import xyz.kd5ujc.schema.fiber.FiberOrdinal

    SecurityProvider.forAsync[IO].use { implicit sp =>
      Participant.ParticipantRegistry.fromResources[IO]().flatMap { registry =>
        val msg: Updates.OttochainMessage = Updates.ArchiveStateMachine(
          fiberId = UUID.randomUUID(),
          targetSequenceNumber = FiberOrdinal.MinValue
        )
        registry.generateProofs(msg, Set(Participant.Alice, Participant.Bob)).map { proofs =>
          expect(proofs.length == 2)
        }
      }
    }
  }
}
