// AUTO-GENERATED by ottochain-sdk/scripts/gen-health-fixtures.ts — do not edit by hand.
// Act 4: pharmacy-corner fills the prescription. CDS OR-of-dhtuple ring proof over the cohort (real branch hidden, j=1); Nf = x_rx·H is witness-bound; message = Nf ‖ pharmacyHex.
export default () => ({
  "eventName": "fill",
  "payload": {
    "proof": {
      "type": "or",
      "e": "0x3dab0c7548ac678c84c1fd10f0ae201f739270541584fa7873be7542f0352b",
      "children": [
        {
          "type": "dhtuple",
          "e": "0x117c7e830296dc855b3d7b66672fa803ee630d5bb7554eb66e3c7b4ca63b1f",
          "z": "0x0071d59470c250674f76f03f631100ff905daa34d5216b35b1a3594ba8831ed0"
        },
        {
          "type": "dhtuple",
          "e": "0x13b32d274075ab4070b0cdbfeeca5ca64839719f07f4f4ca9710500906357d",
          "z": "0x2aaf385b433e80c23d369c2c6665d002229c30e6cbb56fd41f891e35504d36d9"
        },
        {
          "type": "dhtuple",
          "e": "0x36eecc71471081c94e32a6790aa6de6c6334b141ba8602f6e0417622ae9300",
          "z": "0x001fe6a4e91f631352585bf74ea85e2be91333727f1750cf68b35e3167ada1d2"
        },
        {
          "type": "dhtuple",
          "e": "0x098a93a04d5f9180e17eedb073ed0ad6b6fcbdd11fa342f26ad32825fea849",
          "z": "0x00be202f9908812ba70848f2a632deade0c9b7637cd8b41e89dea70eac420411"
        }
      ]
    },
    "nullifier": "0x1f228133c69a21651bb4a3d23361c0564ac6bce9948f8153eddc5e83a27fe65505e3714949ae86e2b5d3937e58a58fe5146073cba461adb590627006c803bf77",
    "pharmacyHex": "0x0afd9986bdf1acac506874640c30b9658ccd4694",
    "message": "0x1f228133c69a21651bb4a3d23361c0564ac6bce9948f8153eddc5e83a27fe65505e3714949ae86e2b5d3937e58a58fe5146073cba461adb590627006c803bf770afd9986bdf1acac506874640c30b9658ccd4694"
  }
});
