// AUTO-GENERATED by scripts/gen-sigma-mixer-fixture.ts — do not edit by hand.
// Deposit 2/4: registers ring point P[1] = x_1·G.
export default () => ({
  eventName: "deposit",
  payload: {
    point: "0x0e11f2a92a7182919200b212df5e09679080284770741be084c8ae74aa1cf50a140722188305b7e8f82e049865621c091e95a94301ae024b2f7bdd7cffd47f4c",
  },
});
