// AUTO-GENERATED by scripts/gen-sigma-mixer-fixture.ts — do not edit by hand.
// Deposit 3/4: registers ring point P[2] = x_2·G.
export default () => ({
  eventName: "deposit",
  payload: {
    point: "0x0f04271cb87e8feb7320d7bd2b76ecaf37277ed843d4717f32605c662edb20c402e1d52b980779d09e6abc0ab450f7f12d38b8dd26913d82128014810438b5b3",
  },
});
