// AUTO-GENERATED by scripts/gen-sigma-mixer-fixture.ts — do not edit by hand.
// Deposit 4/4: registers ring point P[3] = x_3·G.
export default () => ({
  eventName: "deposit",
  payload: {
    point: "0x15554e1cc21861170e41c7935b217fecfbcce18c9be592682a58156af5bff8c92930b6151979705477658cc7b1b6a1aef318cca86720f70d6ce23c2c48c0159f",
  },
});
