// AUTO-GENERATED by scripts/gen-sigma-mixer-fixture.ts — do not edit by hand.
// B2 forged-nullifier: a SECOND spend of the SAME branch under an ATTACKER-CHOSEN Nf' != x_j·H. The shared-z DDH cannot be satisfied for Nf' (H has unknown dlog), so sigma_verify returns false ⇒ ml0. This is the test that proves the OR-of-dhtuple B2 fix.
export default () => ({
  eventName: "withdraw",
  payload: {
    proof: {"type":"or","e":"0xcb5fbeec801c8fe9dcb3bd8a25b8af48e8c4b8ee15116226480e5cd1bb6140","children":[{"type":"dhtuple","e":"0x0392896d72d105116c64d58bf921c6ae761908517b4fe72cc4793e4768cf1f","z":"0x005e69288a573dfdc1ae96a6f0f3d6d339022f11a9af5849c0c41db014a06625"},{"type":"dhtuple","e":"0x7d1427863c97a84400bfb356dbe5b4fff1e5602c0d061553f376f475e21c8f","z":"0x003c33c9a2129115d38da11b35bce6eb2dbc74c5690f307c58f6a67cd25b410d"},{"type":"dhtuple","e":"0xab81e0d462d43a92bb519305ff7a7ad54bbad7e3242474a5aa7db699f84db3","z":"0x14ccae5c9ff4e5c4efc171c64640b3ca0f3d57d3c44555b6c197a471cc7d8c1b"},{"type":"dhtuple","e":"0x1e58f0d3ac8e182e0b394852f806a7cc24820770477ce4fcd57c207ac9ff63","z":"0x007da7f76e5d1238f01ab793b489e2c804d6b7628f339b0505e7c768fcafa064"}]},
    nullifier: "0x283d83fb9edf7c20507e43c2a9baf815304c0c92ceafa32d50eef84ca5337a1403828e7f735b2dc1c904a8985090a7c9f1d43286e2192346ff0e9b55c053327a",
    recipientHex: "0xabababababababababababababababababababab",
    message: "0x283d83fb9edf7c20507e43c2a9baf815304c0c92ceafa32d50eef84ca5337a1403828e7f735b2dc1c904a8985090a7c9f1d43286e2192346ff0e9b55c053327aabababababababababababababababababababab",
  },
});
