// AUTO-GENERATED by scripts/gen-sigma-mixer-fixture.ts — do not edit by hand.
// H2 front-run: honest proof + TAMPERED recipientHex. The message-binding === fails AND the root challenge folded the original message ⇒ sigma_verify false ⇒ ml0 reject.
export default () => ({
  eventName: "withdraw",
  payload: {
    proof: {"type":"or","e":"0xcb5fbeec801c8fe9dcb3bd8a25b8af48e8c4b8ee15116226480e5cd1bb6140","children":[{"type":"dhtuple","e":"0x0392896d72d105116c64d58bf921c6ae761908517b4fe72cc4793e4768cf1f","z":"0x005e69288a573dfdc1ae96a6f0f3d6d339022f11a9af5849c0c41db014a06625"},{"type":"dhtuple","e":"0x7d1427863c97a84400bfb356dbe5b4fff1e5602c0d061553f376f475e21c8f","z":"0x003c33c9a2129115d38da11b35bce6eb2dbc74c5690f307c58f6a67cd25b410d"},{"type":"dhtuple","e":"0xab81e0d462d43a92bb519305ff7a7ad54bbad7e3242474a5aa7db699f84db3","z":"0x14ccae5c9ff4e5c4efc171c64640b3ca0f3d57d3c44555b6c197a471cc7d8c1b"},{"type":"dhtuple","e":"0x1e58f0d3ac8e182e0b394852f806a7cc24820770477ce4fcd57c207ac9ff63","z":"0x007da7f76e5d1238f01ab793b489e2c804d6b7628f339b0505e7c768fcafa064"}]},
    nullifier: "0x278b4053241a6e5a335cf4fbd3170cd36f4891a91082bc099d64537da68c2b702ada91f4c80b6f2de10e1ca108e8e8078ef556d106df840e27433efc1dddff84",
    recipientHex: "0xcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd",
    message: "0x278b4053241a6e5a335cf4fbd3170cd36f4891a91082bc099d64537da68c2b702ada91f4c80b6f2de10e1ca108e8e8078ef556d106df840e27433efc1dddff84abababababababababababababababababababab",
  },
});
