// AUTO-GENERATED by scripts/gen-sigma-mixer-fixture.ts — do not edit by hand.
// Deposit 1/4: registers ring point P[0] = x_0·G.
export default () => ({
  eventName: "deposit",
  payload: {
    point: "0x134d32ea260dbdf60a60af14a44465a555ae12c21f11f55284d690d8501356910d43e8f5dada384f1aab4332a6cb7910428ee144f469362a01e250ae7a9aa432",
  },
});
