package xyz.kd5ujc.shared_data

import cats.effect.IO

import scala.io.Source

import xyz.kd5ujc.schema.GenesisManifest
import xyz.kd5ujc.schema.registry.{RegistryName, RegistryTarget}
import xyz.kd5ujc.shared_data.genesis.GenesisManifestLoader

import io.circe.parser.decode
import weaver.SimpleIOSuite

/**
 * SDK <-> chain CONTRACT guard: the real, checked-in `genesis/std-manifest.json` produced by the
 * ottochain-sdk genesis-manifest exporter (#46) must decode against the chain's [[GenesisManifest]] codecs
 * and build a consistent genesis via [[GenesisManifestLoader]]. This exercises every flagged
 * cross-language concern at once (bare-string StateId, `metadata: null` on states + definition, the
 * projected identity definition, camelCase schemaShape). If the SDK exporter drifts from the chain codecs,
 * this fails. The golden file is regenerated by the SDK's `genesis:manifest` script.
 */
object StdManifestContractSuite extends SimpleIOSuite {

  private val manifestJson: String = {
    val src = Source.fromResource("genesis/std-manifest.json")
    try src.mkString
    finally src.close()
  }

  private val stdNames =
    List("std.identity.package", "std.governance.package", "std.markets.package")

  test("the real ottochain-sdk std manifest decodes + builds a consistent genesis") {
    for {
      manifest <- IO.fromEither(decode[GenesisManifest](manifestJson))
      genesis  <- GenesisManifestLoader.fromManifest[IO](manifest)
    } yield expect(manifest.packages.size == 3) and
    expect(stdNames.forall { n =>
      val name = RegistryName.unsafe(n)
      genesis.calculated.registry.contains(name) && genesis.onChain.registryCommits.contains(name)
    }) and
    expect(genesis.calculated.registry.values.forall(_.target match {
      case RegistryTarget.SchemaPackage(lineage) => lineage.head.exists(_.schemaShape.stateMessage.fields.nonEmpty)
      case _                                     => false
    }))
  }
}
